CREATE TABLE IF NOT EXISTS USER (
	USERID 		  INT(20) NOT NULL AUTO_INCREMENT,
    LOGIN 		  VARCHAR(10) NOT NULL,
    PASSWORD 	  VARCHAR(64) NOT NULL,
    FIRSTNAME 	  VARCHAR(20) NOT NULL,
    LASTNAME 	  VARCHAR(30) NOT NULL,
    SECURITYTOKEN VARCHAR(35) NOT NULL,

    PRIMARY KEY PK_USER (USERID),
    UNIQUE KEY UK_USER_LOGIN (LOGIN),
    UNIQUE KEY UK_USER_SECURITYTOKEN (SECURITYTOKEN)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS LOCATION (
	LOCATIONID 	 INT(20) NOT NULL AUTO_INCREMENT,
    COUNTRY    	 VARCHAR(30) NOT NULL,
    CITY 	   	 VARCHAR(30) NOT NULL,
    STREET 	   	 VARCHAR(35) NOT NULL,
    STREETNUMBER VARCHAR(5) NOT NULL,
    ZIPCODE 	 VARCHAR(10) NOT NULL,
    LATITUDE 	 DECIMAL(10,8) NOT NULL,
    LONGITUDE 	 DECIMAL(11,8) NOT NULL,

    PRIMARY KEY PK_LOCATION (LOCATIONID),
    UNIQUE KEY UK_LOCATION (LATITUDE,LONGITUDE)
) ENGINE = INNODB;

INSERT INTO LOCATION (LOCATIONID, COUNTRY, CITY, STREET, STREETNUMBER, ZIPCODE, LATITUDE, LONGITUDE) VALUES (-1, 'NOT SET', 'NOT SET', 'NOT SET', '-1', 'NOT SET', -1, -1);

CREATE TABLE IF NOT EXISTS PARKINGSLOT (
	PARKINGSLOTID INT(20) NOT NULL AUTO_INCREMENT,
    NAME 		  VARCHAR(30) NOT NULL,
    STARTDATE 	  INT(20) NOT NULL,
    ENDDATE 	  INT(20) NOT NULL,
    ISACTIVE 	  BINARY(1) NOT NULL DEFAULT 1,
    DESCRIPTION   TEXT NULL,
    WIDTH 		  FLOAT(7,2) NULL,
    HEIGHT 		  FLOAT(7,2) NULL,
	COST 		  INT(5) NOT NULL,
    ISDISABLED    BINARY(1) NOT NULL DEFAULT 0,
    LOCATIONID    INT(20) NOT NULL DEFAULT -1,

    PRIMARY KEY PK_PARKINGSLOT (PARKINGSLOTID),
    FOREIGN KEY FK_PARKINGSLOT_LOCATION (LOCATIONID) REFERENCES LOCATION(LOCATIONID)
				ON UPDATE CASCADE ON DELETE RESTRICT,
	UNIQUE KEY UK_PARKINGSLOT (NAME)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS PHOTO (
	PHOTOID 	  INT(20) NOT NULL AUTO_INCREMENT,
    PATH 		  VARCHAR(1024) NOT NULL,
    PARKINGSLOTID INT(20) NOT NULL,

    PRIMARY KEY PK_PHOTO (PHOTOID),
    FOREIGN KEY FK_PHOTO_PARKINGSLOT (PARKINGSLOTID) REFERENCES PARKINGSLOT(PARKINGSLOTID)
		ON UPDATE CASCADE ON DELETE CASCADE,
	UNIQUE KEY UK_PHOTO (PATH)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS BOOKINGHISTORY (
	BOOKINGID     INT(20) NOT NULL AUTO_INCREMENT,
    STARTDATE     INTEGER(20) NOT NULL,
    ISACTIVE      BINARY(1) NOT NULL DEFAULT 1,
    OWNERID       INT(20) NOT NULL,
    PARKINGSLOTID INT(20) NOT NULL,

    PRIMARY KEY PK_BOOKINGHISTORY (BOOKINGID),
    FOREIGN KEY FK_BOOKINGHISTORY_PARKINGSLOT (PARKINGSLOTID) REFERENCES PARKINGSLOT(PARKINGSLOTID)
		ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE = INNODB;